### ISSUE TITLE
Compiling for Mac OS X El Capitan + AMPPS (PHP 5.6.11)

### ISSUE THREAD

**Issue by alopezruiz** [famsf/pecl-pdo-4d#5]
Hi,

More than an issue is an issue to me because I'm new to this...

Could you be so kind to help me to explain how to compile for El Capitan + AMPPS PHP 5.6.11, or just post pdo_4d.so? **Thanks you**

**I get this error:**

server:PDO alopezruiz$ **make test**
/bin/sh /Users/alopezruiz/Downloads/PDO/libtool --mode=compile cc -I/usr/include/php/ext -I/Users/alopezruiz/Downloads/PDO/lib4d_sql -I. -I/Users/alopezruiz/Downloads/PDO -DPHP_ATOM_INC -I/Users/alopezruiz/Downloads/PDO/include -I/Users/alopezruiz/Downloads/PDO/main -I/Users/alopezruiz/Downloads/PDO -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/usr/include/php/ext -I/usr/include/php/ext/pdo  -DHAVE_CONFIG_H  -g -O2   -c /Users/alopezruiz/Downloads/PDO/lib4d_sql/base64.c -o lib4d_sql/base64.lo 
/Users/alopezruiz/Downloads/PDO/libtool: line 862: X--mode=compile: command not found
/Users/alopezruiz/Downloads/PDO/libtool: line 1029: **\* Warning: inferring the mode of operation is deprecated.: command not found
/Users/alopezruiz/Downloads/PDO/libtool: line 1030: **\* Future versions of Libtool will require --mode=MODE be specified.: command not found
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: Xcc: command not found
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-I/usr/include/php/ext: No such file or directory
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-I/Users/alopezruiz/Downloads/PDO/lib4d_sql: No such file or directory
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-I.: command not found
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-I/Users/alopezruiz/Downloads/PDO: No such file or directory
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-DPHP_ATOM_INC: command not found
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-I/Users/alopezruiz/Downloads/PDO/include: No such file or directory
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-I/Users/alopezruiz/Downloads/PDO/main: No such file or directory
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-I/Users/alopezruiz/Downloads/PDO: No such file or directory
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-I/usr/include/php: No such file or directory
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-I/usr/include/php/main: No such file or directory
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-I/usr/include/php/TSRM: No such file or directory
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-I/usr/include/php/Zend: No such file or directory
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-I/usr/include/php/ext: No such file or directory
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-I/usr/include/php/ext/date/lib: No such file or directory
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-I/usr/include/php/ext: No such file or directory
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-I/usr/include/php/ext/pdo: No such file or directory
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-DHAVE_CONFIG_H: command not found
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-g: command not found
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-O2: command not found
/Users/alopezruiz/Downloads/PDO/libtool: line 1173: X-c: command not found
/Users/alopezruiz/Downloads/PDO/libtool: line 1226: Xlib4d_sql/base64.lo: No such file or directory
/Users/alopezruiz/Downloads/PDO/libtool: line 1231: libtool: compile: cannot determine name of library object from `': command not found
make: **\* [lib4d_sql/base64.lo] Error 1

**Comment by 13rac1** [comment]
Sorry, compilation on OS X is not supported. It might work, but there are many requirements (Xcode, Xcode Command Line Tools, compiled PHP, plus ???) Even if you get it to compile it'll probably still not work with AMPPS.

You need run this on Linux. If you need this on your local machine, I suggest installing Linux either in a separate partition or in virtual machine with [Virtual Box](https://www.virtualbox.org/) or [Vagrant](https://www.vagrantup.com/).

If you install with Vagrant, just use whatever your production server is running.

If you install in VirtualBox, I suggest trying one of the desktop Linux distributions:
- http://www.ubuntu.com/desktop - 14.04 LTS is the only tested compilation target.
- https://getfedora.org/en/workstation/ - If your server is CentOS, Fedora is the closest desktop.
- http://blog.linuxmint.com/?p=2947 - Based on Ubuntu 14.04 LTS and what I run.
- https://elementary.io/ - Based on Ubuntu 14.04 LTS and most like a Mac.

**Comment by andrewtf** [comment]
Closing this issue as per the comment by @eosrei

**Comment by alopezruiz** [comment]
Thanks you very much for your assistance! 

I Have 4D_PDO.so (original version) running in Mountain Lion with AMPPS older.

**Comment by alpini** [comment]
May someone can help me with 4d pdo i use OS X el capitan and need to interact with 4d server v15
